#ABNF 1.0;
language pl-pl;
mode voice;
root $root;
tag-format <semantics/1.0-literals>;

$root = [$zyczenie] $ile_bilety na $naco |
        $ile_bilety na $naco $prosba;

$ile_bilety = [jeden] bilet |
              jeden [bilet] |
              $ile [bilety] |
              $ile2 [biletów];
$naco = ($zespolbiernik) | (koncert $zespoldopelniacz) | (koncert_zespołu $zespolmianownik);

$prosba = poproszę | proszę ;
$zyczenie = (chciałbym | chciałabym | chcę) kupić | $prosba;
$ile2 = pięć {5} | sześć {6} | siedem {7}| osiem {8}| dziewięć {9}| dziesięć{10};
$ile = dwa {2}| trzy {3} | cztery{4};
$zespolmianownik =  Hey {Hey}|
                    Coma {Coma}|
                    Myslovitz {Myslovitz}|
                    Muchy {Muchy}|
                    Piersi {Piersi}|
                    Pidżama [Porno] {Pidżama};
$zespolbiernik = (Hey | Heya){Hey} |
                  Comę {Coma} |
                  Myslovitz {Myslovitz}|
                  Muchy {Muchy} |
                  Piersi {Piersi}|
                  Pidżamę [Porno] {Pidżama};
$zespoldopelniacz = (Hey | Heya) {Hey}|
                     Comy {Coma}|
                     Myslovitz {Myslovitz}|
                     Much {Muchy}|
                     Piersi {Piersi}|
                     (Pidżamy|Pidżama) [Porno] {Pidżama};

