# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pathfinder.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pathfinder.proto',
  package='techmo.speechanalytics.pathfinder',
  syntax='proto3',
  serialized_pb=_b('\n\x10pathfinder.proto\x12!techmo.speechanalytics.pathfinder\x1a\x1bgoogle/protobuf/empty.proto\"\xb9\x01\n\x11SpotPhraseRequest\x12\x43\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x33.techmo.speechanalytics.pathfinder.SpotPhraseConfig\x12\x43\n\x05\x61udio\x18\x02 \x01(\x0b\x32\x32.techmo.speechanalytics.pathfinder.SpotPhraseAudioH\x00\x12\x12\n\x08\x63\x61\x63he_id\x18\x03 \x01(\tH\x00\x42\x06\n\x04\x64\x61ta\"8\n\x10SpotPhraseConfig\x12\x0f\n\x07phrases\x18\x01 \x03(\t\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\"\"\n\x0fSpotPhraseAudio\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"\xb3\x01\n\x12SpotPhraseResponse\x12\x41\n\x07phrases\x18\x01 \x03(\x0b\x32\x30.techmo.speechanalytics.pathfinder.SpottedPhrase\x12H\n\rtranscription\x18\x02 \x03(\x0b\x32\x31.techmo.speechanalytics.pathfinder.RecognizedWord\x12\x10\n\x08\x63\x61\x63he_id\x18\x03 \x01(\t\"J\n\rSpottedPhrase\x12\x0e\n\x06phrase\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\r\n\x05start\x18\x03 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x04 \x01(\x05\"@\n\x0eRecognizedWord\x12\x12\n\ntranscript\x18\x01 \x01(\t\x12\r\n\x05start\x18\x02 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x03 \x01(\x05\"%\n\x11\x44\x65leteDataRequest\x12\x10\n\x08\x63\x61\x63he_id\x18\x01 \x01(\t2\x80\x04\n\nPathfinder\x12y\n\nSpotPhrase\x12\x34.techmo.speechanalytics.pathfinder.SpotPhraseRequest\x1a\x35.techmo.speechanalytics.pathfinder.SpotPhraseResponse\x12\x84\x01\n\x13SpotPhraseStreaming\x12\x34.techmo.speechanalytics.pathfinder.SpotPhraseRequest\x1a\x35.techmo.speechanalytics.pathfinder.SpotPhraseResponse(\x01\x12\x93\x01\n SpotPhraseBidirectionalStreaming\x12\x34.techmo.speechanalytics.pathfinder.SpotPhraseRequest\x1a\x35.techmo.speechanalytics.pathfinder.SpotPhraseResponse(\x01\x30\x01\x12Z\n\nDeleteData\x12\x34.techmo.speechanalytics.pathfinder.DeleteDataRequest\x1a\x16.google.protobuf.EmptyB8\n$pl.techmo.speechanalytics.pathfinderB\x10PathfinderProtosb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_SPOTPHRASEREQUEST = _descriptor.Descriptor(
  name='SpotPhraseRequest',
  full_name='techmo.speechanalytics.pathfinder.SpotPhraseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='config', full_name='techmo.speechanalytics.pathfinder.SpotPhraseRequest.config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='audio', full_name='techmo.speechanalytics.pathfinder.SpotPhraseRequest.audio', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cache_id', full_name='techmo.speechanalytics.pathfinder.SpotPhraseRequest.cache_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='techmo.speechanalytics.pathfinder.SpotPhraseRequest.data',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=85,
  serialized_end=270,
)


_SPOTPHRASECONFIG = _descriptor.Descriptor(
  name='SpotPhraseConfig',
  full_name='techmo.speechanalytics.pathfinder.SpotPhraseConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='phrases', full_name='techmo.speechanalytics.pathfinder.SpotPhraseConfig.phrases', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sample_rate', full_name='techmo.speechanalytics.pathfinder.SpotPhraseConfig.sample_rate', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=328,
)


_SPOTPHRASEAUDIO = _descriptor.Descriptor(
  name='SpotPhraseAudio',
  full_name='techmo.speechanalytics.pathfinder.SpotPhraseAudio',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='techmo.speechanalytics.pathfinder.SpotPhraseAudio.content', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=330,
  serialized_end=364,
)


_SPOTPHRASERESPONSE = _descriptor.Descriptor(
  name='SpotPhraseResponse',
  full_name='techmo.speechanalytics.pathfinder.SpotPhraseResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='phrases', full_name='techmo.speechanalytics.pathfinder.SpotPhraseResponse.phrases', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='transcription', full_name='techmo.speechanalytics.pathfinder.SpotPhraseResponse.transcription', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cache_id', full_name='techmo.speechanalytics.pathfinder.SpotPhraseResponse.cache_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=367,
  serialized_end=546,
)


_SPOTTEDPHRASE = _descriptor.Descriptor(
  name='SpottedPhrase',
  full_name='techmo.speechanalytics.pathfinder.SpottedPhrase',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='phrase', full_name='techmo.speechanalytics.pathfinder.SpottedPhrase.phrase', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='score', full_name='techmo.speechanalytics.pathfinder.SpottedPhrase.score', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start', full_name='techmo.speechanalytics.pathfinder.SpottedPhrase.start', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end', full_name='techmo.speechanalytics.pathfinder.SpottedPhrase.end', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=548,
  serialized_end=622,
)


_RECOGNIZEDWORD = _descriptor.Descriptor(
  name='RecognizedWord',
  full_name='techmo.speechanalytics.pathfinder.RecognizedWord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='transcript', full_name='techmo.speechanalytics.pathfinder.RecognizedWord.transcript', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start', full_name='techmo.speechanalytics.pathfinder.RecognizedWord.start', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end', full_name='techmo.speechanalytics.pathfinder.RecognizedWord.end', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=624,
  serialized_end=688,
)


_DELETEDATAREQUEST = _descriptor.Descriptor(
  name='DeleteDataRequest',
  full_name='techmo.speechanalytics.pathfinder.DeleteDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cache_id', full_name='techmo.speechanalytics.pathfinder.DeleteDataRequest.cache_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=690,
  serialized_end=727,
)

_SPOTPHRASEREQUEST.fields_by_name['config'].message_type = _SPOTPHRASECONFIG
_SPOTPHRASEREQUEST.fields_by_name['audio'].message_type = _SPOTPHRASEAUDIO
_SPOTPHRASEREQUEST.oneofs_by_name['data'].fields.append(
  _SPOTPHRASEREQUEST.fields_by_name['audio'])
_SPOTPHRASEREQUEST.fields_by_name['audio'].containing_oneof = _SPOTPHRASEREQUEST.oneofs_by_name['data']
_SPOTPHRASEREQUEST.oneofs_by_name['data'].fields.append(
  _SPOTPHRASEREQUEST.fields_by_name['cache_id'])
_SPOTPHRASEREQUEST.fields_by_name['cache_id'].containing_oneof = _SPOTPHRASEREQUEST.oneofs_by_name['data']
_SPOTPHRASERESPONSE.fields_by_name['phrases'].message_type = _SPOTTEDPHRASE
_SPOTPHRASERESPONSE.fields_by_name['transcription'].message_type = _RECOGNIZEDWORD
DESCRIPTOR.message_types_by_name['SpotPhraseRequest'] = _SPOTPHRASEREQUEST
DESCRIPTOR.message_types_by_name['SpotPhraseConfig'] = _SPOTPHRASECONFIG
DESCRIPTOR.message_types_by_name['SpotPhraseAudio'] = _SPOTPHRASEAUDIO
DESCRIPTOR.message_types_by_name['SpotPhraseResponse'] = _SPOTPHRASERESPONSE
DESCRIPTOR.message_types_by_name['SpottedPhrase'] = _SPOTTEDPHRASE
DESCRIPTOR.message_types_by_name['RecognizedWord'] = _RECOGNIZEDWORD
DESCRIPTOR.message_types_by_name['DeleteDataRequest'] = _DELETEDATAREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SpotPhraseRequest = _reflection.GeneratedProtocolMessageType('SpotPhraseRequest', (_message.Message,), dict(
  DESCRIPTOR = _SPOTPHRASEREQUEST,
  __module__ = 'pathfinder_pb2'
  # @@protoc_insertion_point(class_scope:techmo.speechanalytics.pathfinder.SpotPhraseRequest)
  ))
_sym_db.RegisterMessage(SpotPhraseRequest)

SpotPhraseConfig = _reflection.GeneratedProtocolMessageType('SpotPhraseConfig', (_message.Message,), dict(
  DESCRIPTOR = _SPOTPHRASECONFIG,
  __module__ = 'pathfinder_pb2'
  # @@protoc_insertion_point(class_scope:techmo.speechanalytics.pathfinder.SpotPhraseConfig)
  ))
_sym_db.RegisterMessage(SpotPhraseConfig)

SpotPhraseAudio = _reflection.GeneratedProtocolMessageType('SpotPhraseAudio', (_message.Message,), dict(
  DESCRIPTOR = _SPOTPHRASEAUDIO,
  __module__ = 'pathfinder_pb2'
  # @@protoc_insertion_point(class_scope:techmo.speechanalytics.pathfinder.SpotPhraseAudio)
  ))
_sym_db.RegisterMessage(SpotPhraseAudio)

SpotPhraseResponse = _reflection.GeneratedProtocolMessageType('SpotPhraseResponse', (_message.Message,), dict(
  DESCRIPTOR = _SPOTPHRASERESPONSE,
  __module__ = 'pathfinder_pb2'
  # @@protoc_insertion_point(class_scope:techmo.speechanalytics.pathfinder.SpotPhraseResponse)
  ))
_sym_db.RegisterMessage(SpotPhraseResponse)

SpottedPhrase = _reflection.GeneratedProtocolMessageType('SpottedPhrase', (_message.Message,), dict(
  DESCRIPTOR = _SPOTTEDPHRASE,
  __module__ = 'pathfinder_pb2'
  # @@protoc_insertion_point(class_scope:techmo.speechanalytics.pathfinder.SpottedPhrase)
  ))
_sym_db.RegisterMessage(SpottedPhrase)

RecognizedWord = _reflection.GeneratedProtocolMessageType('RecognizedWord', (_message.Message,), dict(
  DESCRIPTOR = _RECOGNIZEDWORD,
  __module__ = 'pathfinder_pb2'
  # @@protoc_insertion_point(class_scope:techmo.speechanalytics.pathfinder.RecognizedWord)
  ))
_sym_db.RegisterMessage(RecognizedWord)

DeleteDataRequest = _reflection.GeneratedProtocolMessageType('DeleteDataRequest', (_message.Message,), dict(
  DESCRIPTOR = _DELETEDATAREQUEST,
  __module__ = 'pathfinder_pb2'
  # @@protoc_insertion_point(class_scope:techmo.speechanalytics.pathfinder.DeleteDataRequest)
  ))
_sym_db.RegisterMessage(DeleteDataRequest)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n$pl.techmo.speechanalytics.pathfinderB\020PathfinderProtos'))

_PATHFINDER = _descriptor.ServiceDescriptor(
  name='Pathfinder',
  full_name='techmo.speechanalytics.pathfinder.Pathfinder',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=730,
  serialized_end=1242,
  methods=[
  _descriptor.MethodDescriptor(
    name='SpotPhrase',
    full_name='techmo.speechanalytics.pathfinder.Pathfinder.SpotPhrase',
    index=0,
    containing_service=None,
    input_type=_SPOTPHRASEREQUEST,
    output_type=_SPOTPHRASERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SpotPhraseStreaming',
    full_name='techmo.speechanalytics.pathfinder.Pathfinder.SpotPhraseStreaming',
    index=1,
    containing_service=None,
    input_type=_SPOTPHRASEREQUEST,
    output_type=_SPOTPHRASERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SpotPhraseBidirectionalStreaming',
    full_name='techmo.speechanalytics.pathfinder.Pathfinder.SpotPhraseBidirectionalStreaming',
    index=2,
    containing_service=None,
    input_type=_SPOTPHRASEREQUEST,
    output_type=_SPOTPHRASERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteData',
    full_name='techmo.speechanalytics.pathfinder.Pathfinder.DeleteData',
    index=3,
    containing_service=None,
    input_type=_DELETEDATAREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PATHFINDER)

DESCRIPTOR.services_by_name['Pathfinder'] = _PATHFINDER

# @@protoc_insertion_point(module_scope)
