#!/usr/bin/env bash

echo "Generating Techmo ASR Sarmata - python protobuf/grpc sources."
path_i="../proto/"
path_o="service/"
python3 -m grpc_tools.protoc \
	        -I${path_i} \
            --python_out=${path_o} \
            --grpc_python_out=${path_o} \
            ${path_i}/sarmata_asr.proto

# Fix buggy autogenerated GRPC import
sed -i 's/import sarmata_asr_pb2 as sarmata__asr__pb2/from . import sarmata_asr_pb2 as sarmata__asr__pb2/' ${path_o}/sarmata_asr_pb2_grpc.py

